name: Go
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Test
      run: |
        GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint
        export PATH=$GOPATH/bin:$PATH
        make check
      env:
        GOPATH: /tmp/gopath
